# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='slug_field'),
        ),
    ]
